import tkinter 
root = tkinter.Tk()
root.title("My First Tkinter Program")
root.geometry("1000x500")
widget = tkinter.Label(root, text="Hello World")
widget.config(font=("Arial", 24), bg="lightblue", fg="black")
widget.pack(expand=True, fill='both')
butt=tkinter.Button(root,text="click me",command=lambda:print("Button clicked!"),fg="black",bg="red",font=("Arial", 24))
butt.pack()
root.mainloop()